### PR TITLE
Remove UnsafeSlice and use unsafe.Slice

### PR DESCRIPTION
**Pull request by henrybear327**
References:
- https://github.com/etcd-io/bbolt/pull/713
- https://github.com/etcd-io/bbolt/pull/566

### CODE REVIEW

**Review by fuweid — COMMENTED** [review]
changes look good. I would like to keep it as it's because the original code is still working.
It's not bugfix.

**Comment by ivanvc** [comment]
> changes look good. I would like to keep it as it's because the original code is still working. It's not bugfix.

@fuweid, this backport comes from this comment: https://github.com/etcd-io/bbolt/pull/713/files#r1552336503

**Comment by ahrtr** [comment]
> changes look good. I would like to keep it as it's because the original code is still working.
> It's not bugfix.

I have no strong opinion on this. Either way works for me. Since we will maintain release-1.3 for a long time, so I prefer to update it per golang suggested way to get rid of the deprecated solution.

**Review by fuweid — APPROVED** [review]
LGTM

**Review by ahrtr — APPROVED** [review]

**Pull request merged**
