### PR TITLE
fix: use cobra exactArgs

### PR DESCRIPTION
**Pull request by Elbehery**
Fixes https://github.com/etcd-io/bbolt/issues/727

cc @ahrtr @ivanvc @fuweid @tjungblu

### CODE REVIEW

**Review by ahrtr — APPROVED** [review]
LGTM

Thanks

**Comment by Elbehery** [comment]
@ahrtr we should wait for https://github.com/etcd-io/bbolt/pull/723 to merge first, so that i adjust it accordingly in this PR 🙏🏽

**Comment by ahrtr** [comment]
> @ahrtr we should wait for #723 to merge first, so that i adjust it accordingly in this PR 🙏🏽

This PR is straightforward, I think it can be merged once the test green.
Afterwards please rebase #723.

**Pull request merged**
