### PR TITLE
Update bbolt version to 1.4.0-alpha.0

### PR DESCRIPTION
**Pull request by ahrtr**
Link to https://github.com/etcd-io/bbolt/issues/553

### CODE REVIEW

**Comment by ahrtr** [comment]
cc @fuweid @tjungblu @Elbehery

**Comment by Elbehery** [comment]
LGTM

**Review by fuweid — APPROVED** [review]
LGTM

**Comment by tjungblu** [comment]
/lgtm

Thanks @ahrtr :)

**Pull request merged**
