### PR TITLE
seperate cli and cmd main package

### PR DESCRIPTION
**Pull request by iraj720**
hi @serathius
according to this issue that you have raised im trying to embed bbolt to etcdutl cli :
https://github.com/etcd-io/etcd/issues/15760

i have seperated main functionalities of commands in cli package
now it will be easier for etcdutl to easily import this cli package and embed it to its own
and we wont face any versioning issue in there

if it looks good i can start to integrate etcdutl code based on this.
let me know if you have any better suggestion.
Thanks!

### CODE REVIEW

**Comment by serathius** [comment]
Looks good, cc @ahrtr

**Comment by ahrtr** [comment]
I am supportive to move commands into a separate package/directory, but I'd suggest to do such structure change after 
- we cut the release-1.4 branch (pls see https://github.com/etcd-io/bbolt/issues/553)
- we finish https://github.com/etcd-io/bbolt/issues/472 (Will only be included in bbolt 2.0)

After above two things are done, then we can move all commands into a separate package/directory in bbolt 2.0. Afterwards, it would just need very minor change to get it embedded into etcdutl (https://github.com/etcd-io/etcd/issues/15760)

**Comment by iraj720** [comment]
@ahrtr 
seems surgery commands and logger are ready to merge
so meanwhile we are merging them i will migrate all commands to cobra style.
then we can release 1.4 and merge this one then etcdutl will use this one.
is that ok?

**Review by ahrtr — CHANGES_REQUESTED** [review]
Explicitly mark this PR as "Request changes". 

Let's revisit this PR after the two tasks mentioned in https://github.com/etcd-io/bbolt/pull/564#issuecomment-1713495137 are done.

**Comment by ahrtr** [comment]
Sorry, the PR is automatically closed after renaming the master to main. Please feel free to submit a new PR.

**Comment by ahrtr** [comment]
@iraj720 We already cut the release-1.4 branch and released v1.4.0.  Please feel free to deliver a new PR, thx.

**Pull request closed without merging**
