### PR TITLE
dep: upgraded golang.org/x/sys

### LINKED ISSUE #348: `bbolt` CLI fails to compile with linker errors
## Error

When I try to install the CLI tool with `go install -v go.etcd.io/bbolt/cmd/bbolt@latest`, it throws this compile-time error.

```go
golang.org/x/sys/unix
# golang.org/x/sys/unix
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200923182605-d9f96fdee20d/unix/syscall_darwin.1_13.go:29:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200923182605-d9f96fdee20d/unix/zsyscall_darwin_arm64.1_13.go:27:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200923182605-d9f96fdee20d/unix/zsyscall_darwin_arm64.1_13.go:40:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200923182605-d9f96fdee20d/unix/zsyscall_darwin_arm64.go:28:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200923182605-d9f96fdee20d/unix/zsyscall_darwin_arm64.go:43:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200923182605-d9f96fdee20d/unix/zsyscall_darwin_arm64.go:59:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200923182605-d9f96fdee20d/unix/zsyscall_darwin_arm64.go:75:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200923182605-d9f96fdee20d/unix/zsyscall_darwin_arm64.go:90:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200923182605-d9f96fdee20d/unix/zsyscall_darwin_arm64.go:105:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200923182605-d9f96fdee20d/unix/zsyscall_darwin_arm64.go:121:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200923182605-d9f96fdee20d/unix/zsyscall_darwin_arm64.go:121:3: too many errors
```

Here is the macOS info.

image

It looks like golang/go#49219 is the cause, so I'll submit a PR for it.

### PR DESCRIPTION
**Pull request by mxplusb**
Upgraded golang.org/x/sys from v0.2.0 to account for golang/go#49219.

Fixes #348 

Signed-off-by: Sienna Lloyd <sienna@linux.com>

### CODE REVIEW

**Comment by ahrtr** [comment]
Thanks @mxplusb for the PR. I would suggest to wait for the next tag version (e.g. v0.3.0). You can use golang 1.17 to execute `go install ...` command, or build it directly if you want to use golang 1.18 or 1.19.

**Comment by ptabor** [comment]
```
ptab-macbookpro2:bbolt ptab$ go version
go version go1.19.4 darwin/arm64

ptab-macbookpro2:bbolt ptab$ go install -v go.etcd.io/bbolt/cmd/bbolt@latest
go: downloading golang.org/x/sys v0.0.0-20200923182605-d9f96fdee20d
golang.org/x/sys/internal/unsafeheader
golang.org/x/sys/unix
go.etcd.io/bbolt
go.etcd.io/bbolt/cmd/bbolt
```

So it worked... and it downloded 20200923 version despite having `require golang.org/x/sys v0.2.0`

**Comment by ptabor** [comment]
Actually there is v0.3.0 already: https://pkg.go.dev/golang.org/x/sys?tab=versions

**Comment by ahrtr** [comment]
Thanks @ptabor .

@mxplusb Would you mind updating this PR to bump to v0.3.0?

**Comment by ahrtr** [comment]
Resolved in https://github.com/etcd-io/bbolt/pull/356

**Pull request closed without merging**
