### PR TITLE
Update buildtags

### PR DESCRIPTION
**Pull request by philoserf**
Update build tags via `go fix`

### CODE REVIEW

**Review by ivanvc — APPROVED** [review]
LGTM. Verified that `go fix` removes these comments. Thanks for your first contribution, @philoserf!

**Review by ahrtr — APPROVED** [review]
Thanks.

It would be better if we can improve the workflow check to automatically detect & fix such case.

**Comment by ivanvc** [comment]
> Thanks.
> 
> It would be better if we can improve the workflow check to automatically detect & fix such case.

I agree. I was thinking something like what we have in the etcd repository and introducing a `verify` make target that runs the static checks.

**Pull request merged**
