### PR TITLE
Add `surgery clear-elements` command

### PR DESCRIPTION
**Pull request by ahrtr**
This PR is on top of https://github.com/etcd-io/bbolt/pull/407. It can be used to fix the corrupted db file in https://github.com/etcd-io/bbolt/issues/402. 

Steps to fix the db file are as below. 
```
$ ./bbolt surgery clear-elements ./local-kv.db  new1.db 29 5 6

$ ./bbolt surgery clear-elements  ./new1.db ./new2.db 29 7 8

$ ./bbolt surgery clear-elements  ./new2.db ./new3.db 29 9 10
```

`new3.db` is the final db file,
```
$ ./bbolt check ./new3.db 
OK
```

Note we still need to investigate the root cause of the corruption.

### CODE REVIEW

**Comment by ahrtr** [comment]
Still need to add a couple of unit test cases

**Comment by shippomx** [comment]
> Still need to add a couple of unit test cases



> This PR is on top of #407. It can be used to fix the corrupted db file in #402.
> 
> Steps to fix the db file are as below.
> 
> ```
> $ ./bbolt surgery clear-elements ./local-kv.db  new1.db 29 5 6
> 
> $ ./bbolt surgery clear-elements  ./new1.db ./new2.db 29 7 8
> 
> $ ./bbolt surgery clear-elements  ./new2.db ./new3.db 29 9 10
> ```
> 
> `new3.db` is the final db file,
> 
> ```
> $ ./bbolt check ./new3.db 
> OK
> ```
> 
> Note we still need to investigate the root cause of the corruption.



> This PR is on top of #407. It can be used to fix the corrupted db file in #402.
> 
> Steps to fix the db file are as below.
> 
> ```
> $ ./bbolt surgery clear-elements ./local-kv.db  new1.db 29 5 6
> 
> $ ./bbolt surgery clear-elements  ./new1.db ./new2.db 29 7 8
> 
> $ ./bbolt surgery clear-elements  ./new2.db ./new3.db 29 9 10
> ```
> 
> `new3.db` is the final db file,
> 
> ```
> $ ./bbolt check ./new3.db 
> OK
> ```
> 
> Note we still need to investigate the root cause of the corruption.

Thanks, It works for me.

**Comment by ptabor** [comment]
I know it's not how bbolt used to be doing the syntax, but maybe starting with new commands and bbolt 1.4, 
we should be using more readable (cobra style) syntax, like:

`./bbolt surgery clear-page-elements ./local-kv.db  --output ./local-kv.db.new --pageId 57  --from-key=5 --to-key=6`

WDYT ?

**Comment by ahrtr** [comment]
Makes sense to me. I have been thinking to refactor the CMD using cobra. I am thinking to finish the refactoring firstly. WDYT? @ptabor @tjungblu

**Comment by ahrtr** [comment]
> I don't think we need an upfront refactoring

Sounds good to me. I will try to add the new command using cobra. And refactoring other commands in separate PRs later.

**Comment by ahrtr** [comment]
This PR will be superseded by https://github.com/etcd-io/bbolt/pull/417

**Pull request closed without merging**
