### PR TITLE
Add changelog for 1.4.0-beta.0

### PR DESCRIPTION
**Pull request by ahrtr**
Link to https://github.com/etcd-io/bbolt/issues/553

### CODE REVIEW

**Comment by ivanvc** [comment]
Sorry about the robustness failure. It's due to a prow infra current limitation, I'm aware and tracking it.

Should we add a note regarding Go 1.23.2? I see that previous releases did mention the Go version used (#836).

**Comment by ahrtr** [comment]
> Should we add a note regarding Go 1.23.2? I see that previous releases did mention the Go version used (#836).

Thanks for the reminder. Updated the changelog to only mention that it requires 1.23.x.  bbolt is used as a library, it's up to users/application to decide the exact go version. We just need to clear call out the minor go version.



> It's due to a prow infra current limitation, I'm aware and tracking it.

Thanks. If it needs a long time to resolve the issue (i.e. > 2 months), can we add it back to github for now (without arm64)?

**Comment by ivanvc** [comment]
> Thanks. If it needs a long time to resolve the issue (i.e. > 2 months), can we add it back to github for now (without arm64)?

PTAL at kubernetes/test-infra#33735. I say let's hold them to avoid the noise. Restoring them should be quick.

**Review by ivanvc — APPROVED** [review]
LGTM. Thanks, @ahrtr.

**Comment by ahrtr** [comment]
cc @fuweid @jmhbnz @serathius @tjungblu for awareness

**Pull request merged**
