### PR TITLE
return fast for array freelist allocate when requesting zero pages

### PR DESCRIPTION
**Pull request by andyxning**
This PR will return fast for array freelist allocate function when requesting zero page.

### CODE REVIEW

**Comment by xiang90** [comment]
will this improve the previous? when will boltdb ask for a 0 size allocation?

**Comment by andyxning** [comment]
> will this improve the previous? when will boltdb ask for a 0 size allocation?

Actually, i am not quite sure about this for now. I have just begun learning bolt this week. I make this PR because that there exists 0 size allocation in the ut. FYI: https://github.com/etcd-io/bbolt/blob/35b666109344c1547e0135d0d17486746cc073f3/freelist_test.go#L232

**Comment by ahrtr** [comment]
boltDB will never allocate 0 page, otherwise it's a bug.

**Pull request closed without merging**
