### PR TITLE
feat: adapts to Android 14

### PR DESCRIPTION
**Pull request by monkeyWie**
Hi, this PR is fix for https://github.com/etcd-io/bbolt/issues/558, and I created a repository to reproduce it, refer to https://github.com/monkeyWie/bbolt-test

### CODE REVIEW

**Review by jmhbnz — COMMENTED** [review]
Hey @monkeyWie - Thanks for putting this together.  Can you please ensure your commit is signed so your contribution can be accepted, i.e:

```bash
git rebase --signoff HEAD~1

git push --force
```

As a more general comment, how do we have assurance moving forward that the android side of this will continue to work as expected. Is there some way we can excercise this with meaningful tests?

**Comment by monkeyWie** [comment]
I've already signed it, and regarding testing on Android, maybe we can add test cases on github action.

**Comment by ahrtr** [comment]
Have you verified the PR on Android?

**Comment by monkeyWie** [comment]
@ahrtr Sure, I modified go.mod to replace `go.etcd.io/bbolt` with `github.com/monkeyWie/bbolt` and it tested fine, no crashes on Android 14.

**Comment by ahrtr** [comment]
LGTM

Note: The new file is almost identical to https://github.com/etcd-io/bbolt/blob/master/bolt_solaris.go.

**Review by ahrtr — APPROVED** [review]

**Review by jmhbnz — APPROVED** [review]

**Pull request merged**
