### PR TITLE
[1.3] backport go-dmflakey and robustness test

### PR DESCRIPTION
**Pull request by fuweid**
cherry-pick:

* https://github.com/etcd-io/bbolt/pull/622
* https://github.com/etcd-io/bbolt/pull/623
* https://github.com/etcd-io/bbolt/pull/628

### CODE REVIEW

**Comment by fuweid** [comment]
ping @ahrtr @tjungblu

**Comment by tjungblu** [comment]
nice! do you mind to pick #707 along with it?

**Comment by fuweid** [comment]
> nice! would you mind to pick #707 along with it?

It's in my list. I will handle it in the follow-up, since I need to cherry-pick some failpoints first. :)

**Comment by tjungblu** [comment]
sounds good!

/lgtm

**Review by ahrtr — APPROVED** [review]
LGTM

Thank you!

**Pull request merged**
