### PR TITLE
Fix typo in db go

### PR DESCRIPTION
**Pull request by TheAlyxGreen**
Fixed a couple of typos in db.go by changing "framentation" to "fragmentation"

### CODE REVIEW

**Review by spzala — COMMENTED** [review]
@TheAlyxGreen thanks for the PR! Please stash your commits into one and sign-off it to pass the DCO (i.e. add a last line in commit in this format, `Signed-off-by: firstname lastname <email@example.com>`

**Comment by ahrtr** [comment]
Please
1. rebase this PR;
2. squash the commits;
3. signoff the commit: git rebase HEAD~1 --signoff

**Comment by ahrtr** [comment]
Added label resurrection because there is no response from the original author. Please anyone else feel free to resurrect this PR.

**Comment by ahrtr** [comment]
Fixed along with https://github.com/etcd-io/bbolt/pull/383

**Pull request closed without merging**
