### PR TITLE
[1.3] Bump Go version to 1.21.12: GO-2024-2963 fix

### PR DESCRIPTION
**Pull request by thedtripp**
https://github.com/etcd-io/etcd/issues/18269

### CODE REVIEW

**Review by ahrtr — APPROVED** [review]
LGTM

Thanks

**Review by ivanvc — APPROVED** [review]
LGTM. Thanks, @thedtripp

**Comment by ivanvc** [comment]
@ahrtr, we want a 1.3 CHANGELOG entry for this, right?

**Comment by ahrtr** [comment]
> @ahrtr, we want a 1.3 CHANGELOG entry for this, right?

bbolt is used as a library, so its go version doesn't matter. We only need to clarify the minimun golang version to run bbolt, e.g 1.21 for now. It has already clarified in go.mod,

https://github.com/etcd-io/bbolt/blob/71159e32bfdee3f47d391c60d36654192b4664b9/go.mod#L3

Regarding golang patch version, we actually do not care much about it. The motivation to bump goalng patch version is to clear security noise (false positive).

So I tend not to update changelog for it.

[Previously we updated changelog for 1.3.10, not a big deal, let's just keep it as it's.]

**Pull request merged**
