### PR TITLE
Add log

### PR DESCRIPTION
**Pull request by Elbehery**
This PR add logger to bbolt, see https://github.com/etcd-io/raft/blob/main/logger.go

Fixes https://github.com/etcd-io/bbolt/issues/509 

This PR is a continuation of https://github.com/etcd-io/bbolt/pull/513

cc @ahrtr @fuweid

### CODE REVIEW

**Comment by Elbehery** [comment]
@ahrtr had to rebase because the last commit i cherrypicked had no sign-off :/

**Comment by tjungblu** [comment]
lgtm, generally. Why are we rolling our own logger based on go/log btw?

**Comment by Elbehery** [comment]
Thanks @tjungblu  

We can use diff logger, but we follow the same as in `etcd`

**Comment by ahrtr** [comment]
> Why are we rolling our own logger based on go/log btw?

Please read conversation in https://github.com/etcd-io/bbolt/issues/509, especially https://github.com/etcd-io/bbolt/issues/509#issuecomment-1657926396

**Review by fuweid — APPROVED** [review]
LGTM

**Comment by Elbehery** [comment]
can we merge this ?

**Comment by fuweid** [comment]
ping @ahrtr @serathius

**Pull request merged**
