### PR TITLE
Bump go toolchain to 1.23.3

### PR DESCRIPTION
**Pull request by samuelbartels20**
…uel20@gmail.com>
Please review

### CODE REVIEW

**Comment by henrybear327** [comment]
@samuelbartels20 please update the PR title :) Thanks!

**Comment by samuelbartels20** [comment]
> @samuelbartels20 please update the PR title :) Thanks!

@henrybear327 Please i don't understand. Could you please elaborate what you mean?

**Comment by ivanvc** [comment]
Link to https://github.com/etcd-io/etcd/issues/18847

**Comment by henrybear327** [comment]
> > @samuelbartels20 please update the PR title :) Thanks!
> 
> 
> 
> @henrybear327 Please i don't understand. Could you please elaborate what you mean?

Sorry that I just saw your message. 

It's done by @ivanvc already!

**Review by ivanvc — APPROVED** [review]
LGTM. Thanks, @samuelbartels20

**Pull request merged**
