### PR TITLE
[1.3] Rollback alloc map: remove all page ids which are allocated by the txid

### PR DESCRIPTION
**Pull request by ahrtr**
Backport https://github.com/etcd-io/bbolt/pull/819 to 1.3

cc @fuweid @tjungblu

### CODE REVIEW

**Comment by ahrtr** [comment]
Fix https://github.com/etcd-io/bbolt/issues/797 in 1.3

**Review by fuweid — APPROVED** [review]
/lgtm

**Comment by fuweid** [comment]
I think there will be new point release for 1.3 :)

**Comment by ahrtr** [comment]
> I think there will be new point release for 1.3 :)

OK, I will release a new patch soon.

**Pull request merged**
