### PR TITLE
refactor: merge bolt and guts_cli

### PR DESCRIPTION
**Pull request by ahrtr**
Points:
1. There are lots of duplicated definitions between bolt and guts_cli, which is definitely not good.
2. The implementation in guts_cli also has issue, please refer to https://github.com/etcd-io/bbolt/issues/391. This refactoring can fix the issue.

Moved all common definitions into package `internal/common`. Majority other changes are basically mechanical changes. 

Signed-off-by: Benjamin Wang <wachao@vmware.com>

### CODE REVIEW

**Comment by ptabor** [comment]
I support the direction. Thank you for this refactoring. 

The plan I was thinking about assumed: 
  - releasing v1.3.6. 
  - doing bigger refactoring as part of v1.4.0 line (such that potential regressions within 1.3.x line are easy to follow). 

v1.3.5 is already 2.5 year old.

**Comment by ahrtr** [comment]
> v1.3.5 is already 2.5 year old.

Actually v1.3.6 was released Jun 2, 2021.
https://github.com/etcd-io/bbolt/releases/tag/v1.3.6

I agree to release 1.3.7 firstly.  Let me trigger a pipeline to verify bolt in etcd's pipeline, if there is no any issue, then we can tag v1.3.7

**Comment by ptabor** [comment]
Indeed it was tagged (and used in etcd) but not publised on: https://github.com/etcd-io/bbolt/releases

**Comment by ahrtr** [comment]
v1.3.7 is already released, this PR will only target v1.4.0.

**Comment by ahrtr** [comment]
@ptabor could you please take a look this PR? I am planning to fix the following two issues on top of this PR,
- https://github.com/etcd-io/bbolt/issues/391
- https://github.com/etcd-io/bbolt/issues/402

**Comment by ptabor** [comment]
@ahrtr : I assume its obsoleted by: https://github.com/etcd-io/bbolt/pull/407.

**Comment by ahrtr** [comment]
> @ahrtr : I assume its obsoleted by: #407.

@ptabor  exactly.

**Comment by ahrtr** [comment]
Closing this PR, and let me continue to work on https://github.com/etcd-io/bbolt/pull/407

**Pull request closed without merging**
