### PR TITLE
Move `copyFile` into internal/common/util.go

### PR DESCRIPTION
**Pull request by ahrtr**
Extracted from https://github.com/etcd-io/bbolt/pull/442, so that it can be reviewed and merged separately.

### CODE REVIEW

**Review by jmhbnz — APPROVED** [review]
This looks good to me.

I do have one question, there is an identically named function `func (tx *Tx) CopyFile` in `tx.go` and that file already imports `go.etcd.io/bbolt/internal/common`.
 Implementation is quite a bit different so this might be totally fine I am just wondering if there is any benefit from attempting to re-use just one function?

**Comment by ahrtr** [comment]
It's a good question.

In order to use  `(tx *Tx) CopyFile`, we need to create a transaction firstly. When the test fails and db file somehow corrupts, it may not successfully create the transaction. So We need to make sure the implementation of CopyFile independent on the bbolt transaction itself.

**Comment by ahrtr** [comment]
cc @ptabor

**Review by ptabor — APPROVED** [review]

**Comment by ahrtr** [comment]
thx @ptabor

**Pull request merged**
