### PR TITLE
[1.3] backport failpoints(resizeFileError, lackOfDiskSpace) and dmflakey on XFS

### PR DESCRIPTION
**Pull request by fuweid**
cherry-pick:

* https://github.com/etcd-io/bbolt/pull/482
* https://github.com/etcd-io/bbolt/pull/546 (without using errors package)
* https://github.com/etcd-io/bbolt/pull/658
* https://github.com/etcd-io/bbolt/pull/707 (remove robustness-template and add `apt install xfsprogs` in robustness.yaml)

### CODE REVIEW

**Comment by ahrtr** [comment]
cc @tjungblu

**Comment by tjungblu** [comment]
/lgtm

thank you @fuweid

**Review by ahrtr — APPROVED** [review]
LGTM

**Comment by ahrtr** [comment]
@fuweid the robustness test failed right after merging this PR, can you take a look? thx
https://github.com/etcd-io/bbolt/actions/runs/10316542012/job/28558983342 

cc @tjungblu

**Comment by fuweid** [comment]
> @fuweid the robustness test failed right after merging this PR, can you take a look? thx https://github.com/etcd-io/bbolt/actions/runs/10316542012/job/28558983342
> 
> cc @tjungblu

=== RUN   TestRestartFromPowerFailureExt4/fp_ext4_commit1s
    powerfailure_test.go:168: start bbolt bench -work -path /tmp/TestRestartFromPowerFailureExt4fp_ext4_commit1s37063[42](https://github.com/etcd-io/bbolt/actions/runs/10316542012/job/28558983342#step:5:43)47/002/boltdb -count=1000000000 -batch-size=5
    powerfailure_test.go:185: simulate power failure
    powerfailure_test.go:190: random pick failpoint: mapError
    powerfailure_test.go:199: **bbolt should stop with panic in seconds**

The bbolt command wasn't panic in 10 seconds.

**Comment by fuweid** [comment]
I need to backport this one as well

https://github.com/etcd-io/bbolt/commit/49eb212fa8ab67709ea460df01982504cf7fa4a1

**Pull request merged**
