### PR TITLE
Migrate to go1.22

### PR DESCRIPTION
**Pull request by dusk125**
Part of https://github.com/etcd-io/etcd/issues/17348.
bbolt tests successfully locally.

### CODE REVIEW

**Comment by dusk125** [comment]
@ahrtr @serathius ptal

**Review by serathius — APPROVED** [review]

**Comment by ahrtr** [comment]
Failed on windows

```
find: paths must precede expression: `bolt_386.go'
find: possible unquoted pattern after predicate `-name'?
hashmap freelist test
BBOLT_VERIFY=all TEST_FREELIST_TYPE=hashmap go test -v -race=false -cpu=4  -timeout 30m
go.etcd.io/bbolt/errors: cannot compile Go 1.22 code
FAIL	go.etcd.io/bbolt [build failed]
make: *** [Makefile:45: test] Error 1
Error: Process completed with exit code 2.
```

**Review by ahrtr — CHANGES_REQUESTED** [review]
Please take a look at the failure on Windows

**Comment by ahrtr** [comment]
@dusk125 @jmhbnz could you take a look at the workflow failure? It looks like somehow the go version/env hasn't been setup successfully on Windows.

**Review by ahrtr — APPROVED** [review]

**Pull request merged**
