### PR TITLE
Panicking when a write txn tries to free a page which was allocated by itself

### PR DESCRIPTION
**Pull request by ahrtr**
A writing TXN should never free a page which was allocated by itself.

Link to https://github.com/etcd-io/bbolt/issues/789

### CODE REVIEW

**Comment by tjungblu** [comment]
testcase that triggers this panic:

https://github.com/etcd-io/bbolt/compare/main...tjungblu:cache_freelist_inconsistency?expand=1#diff-3d69c5fb9cdafd3a4e75384354f4a9e14b5318b0e4ec549000cfebd1ac3c6b1bR183-R202

**Comment by ahrtr** [comment]
> https://github.com/etcd-io/bbolt/compare/main...tjungblu:cache_freelist_inconsistency?expand=1#diff-3d69c5fb9cdafd3a4e75384354f4a9e14b5318b0e4ec549000cfebd1ac3c6b1bR183-R202

line 194, it tries to free a page which was just allocated by itself. You can do this in a unit test, but actually it will never happen in real production use case.

```
f.free(common.Txid(2), common.NewPage(allocate, common.LeafPageFlag, 0, 1))
```

**Comment by tjungblu** [comment]
I'm not saying it's a production issue, I was merely testing all the branches ;-)
If it's not allowed, the panic is the correct way to continue with this.

**Comment by ahrtr** [comment]
Just rebased this PR, PTAL @fuweid @tjungblu

**Comment by tjungblu** [comment]
still looks good!

/lgtm

**Comment by ahrtr** [comment]
Just rebased this PR, PTAL @fuweid @tjungblu

**Review by fuweid — APPROVED** [review]

**Pull request merged**
