### PR TITLE
Update changelog for 1.3.10

### PR DESCRIPTION
**Pull request by ahrtr**
Link to https://github.com/etcd-io/bbolt/issues/746

cc @Elbehery @fuweid @ivanvc @tjungblu

### CODE REVIEW

**Review by fuweid — APPROVED** [review]
/lgtm

**Review by ivanvc — APPROVED** [review]
LGTM :+1:

**Comment by serathius** [comment]
Note, as a library bbolt should not announce updates to Go version used it CI. It's not very relevant, also we should avoid bumping go version in `go.mod` on stable releases as it means we drop support of older Go version which is a breaking change. 

Instead of bumping go version in `go.mod` we should add a separate CI job that tests multiple go version for compatibility.

**Comment by ahrtr** [comment]
> Note, as a library bbolt should not announce updates to Go version used it CI.

It isn't announcing the go version used in CI; instead it's announce the min go version to run bbolt. I was thinking to add `toolchain go1.21.9` in 1.3's go.mod file, still think we should add it.



> we should add a separate CI job that tests multiple go version for compatibility.

No unless there are LTS go versions in future 
- Why should we support go versions which are already out of support by golang team?
- Usually the only reason to bump go version for stable release is to resolve CVE or any critical bugs.

**Comment by fuweid** [comment]
Sometimes, higher go versions might break existing lint or remove deprecated features. 
In the meantimes, the maintainers uses higher go versions to test the library or build binary, like CI pipeline.
When we bump the .go-version, it's likely, potentially to break the build which uses non-supported go versions. 
It's unlikely to catch it in CI pipeline (because we use higher go version) or by eyeball review.

For me, bumping go version is like explicit note that please update go version before use.
It's friendly for user if there is any CVE fix in supported go version.

**Comment by ahrtr** [comment]
> Sometimes, higher go versions might break existing lint or remove deprecated features.

Theoretically yes, but practically highly unlikely for bbolt. But if we see any such case, we need to clear clarify it in doc.

**Pull request merged**
